#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Back-End
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_back_end }}"
    state: present

  #loop
  with_items: "{{ groups_ad_back_end }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Front-End
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_front_end }}"
    state: present

  #loop
  with_items: "{{ groups_ad_front_end }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Suporte Tecnico
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_suporte_tecnico }}"
    state: present

  #loop
  with_items: "{{ groups_ad_suporte_tecnico }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Redes e Servidores
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_redes_servidores }}"
    state: present

  #loop
  with_items: "{{ groups_ad_redes_servidores }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Admissoes e Pessoal
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_admissoes_pessoal }}"
    state: present

  #loop
  with_items: "{{ groups_ad_admissoes_pessoal }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Desenvolvimento Humano
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_desenvolvimento_humano }}"
    state: present

  #loop
  with_items: "{{ groups_ad_desenvolvimento_humano }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Administrativo-Financeiro
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_financeiro }}"
    state: present

  #loop
  with_items: "{{ groups_ad_financeiro }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Compras e Logistica
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_compras_logistica }}"
    state: present

  #loop
  with_items: "{{ groups_ad_compras_logistica }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Projetos Estrategicos
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_projetos_estrategicos }}"
    state: present

  #loop
  with_items: "{{ groups_ad_projetos_estrategicos }}"
#-------------------Fim-------------------------------------

#-------------------Inicio--------------------------------------
- name: Adcionando usuario na Unidade Organizacional Parcerias e convenios
  win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    state: present
    path: "{{ caminho_dominio_parcerias_convenios }}"
    state: present

  #loop
  with_items: "{{ groups_ad_parcerias_convenios }}"
#-------------------Fim-------------------------------------

