- hosts: windows
  gather_facts: no

  var:
    caminho_dominio: "OU=Diretoria Executiva,DC=xpto,DC=local"
    senha_padrao: "Ifro123456"

    back_End:
    - maria
    - joao
    - fred

    front_End:
    - peach
    - plum
    - pear

    roles:
    - windows_ou