- name: Adicionar usuario ao AD
  microsoft.ad.user:
    identity: "{{ item.name }}"
    password: "{{ senha_padrao }}"
    state: present
    path: "{{ caminho_dominio_back_end }}"
  
  loop: "{{ back_end }}"
  no_log: true
